# Устанавливаем переменные окружения
API_KEY = live_28x7IJCL05al8bakz2LhFdXBNEvl37dQs5KBia9iAWKNorGQPRWM9eBgHEcmNVRB
APP_PORT = 8080

# Запускаем приложение
@API_KEY=$(API_KEY) APP_PORT=$(APP_PORT) ./bin/darwin_arm64
